archives={
    "2018":[
         {'nom':"L'As du Fallafel",
            'num':34,
            'rue':'Rue des Rosiers',
            'lat':48.85741,
            'lon':2.359049,
            'pos': 1,
            'note': 4.4,
            'votes':1200
            },
            {'nom':'Eataly',
            'num': 37,
            'rue':'Rue Sainte-Croix de la Bretonnerie',
            'lat': 48.858673,
            'lon':2.354529,
            'pos': 2,
            'note': 4.4,
            'votes':1300
            },
            {'nom':'Don Giovanni',
            'num':19,
            'rue':'Rue François Miron',
            'lat':48.855731,
            'lon':2.357172,
            'pos': 3,
            'note': 4.7,
            'votes':631
            },
    ],
    "2019":[
         {'nom':"L'As du Fallafel",
            'num':34,
            'rue':'Rue des Rosiers',
            'lat':48.85741,
            'lon':2.359049,
            'pos': 1,
            'note': 4.4,
            'votes':2500
            },
            {'nom':'Don Giovanni',
            'num':19,
            'rue':'Rue François Miron',
            'lat':48.855731,
            'lon':2.357172,
            'pos': 2,
            'note': 4.7,
            'votes':230
            },
            {'nom':'Eataly',
            'num': 37,
            'rue':'Rue Sainte-Croix de la Bretonnerie',
            'lat': 48.858673,
            'lon':2.354529,
            'pos': 3,
            'note': 4.4,
            'votes':3000
            },
    ],
    "2020":[
         {'nom':"L'As du Fallafel",
            'num':34,
            'rue':'Rue des Rosiers',
            'lat':48.85741,
            'lon':2.359049,
            'pos': 1,
            'note': 4.4,
            'votes':8560
            },
            {'nom':'Le Chalet du Grand Palais',
            'num': 9,
            'rue':'Av.des Champs-Élysées',
            'lat':48.869214,
            'lon':2.309979,
            'pos': 2,
            'note': 4.2,
            'votes':11
            },
            {'nom':'Eataly',
            'num': 37,
            'rue':'Rue Sainte-Croix de la Bretonnerie',
            'lat': 48.858673,
            'lon':2.354529,
            'pos': 2,
            'note': 4.4,
            'votes':11000
            },
    ],
    "2021":[ {'nom':"L'As du Fallafel",
            'num':34,
            'rue':'Rue des Rosiers',
            'lat':48.85741,
            'lon':2.359049,
            'pos': 1,
            'note': 4.4,
            'votes':10000
            },
            {'nom':'PavYllon',
            'num': 8,
            'rue':'Av. Dutuit',
            'lat':48.865974,
            'lon':2.315667,
            'pos': 2,
            'note': 4.5,
            'votes':1195
            },
            {'nom':'Eataly',
            'num': 37,
            'rue':'Rue Sainte-Croix de la Bretonnerie',
            'lat': 48.858673,
            'lon':2.354529,
            'pos': 3,
            'note': 4.4,
            'votes':12650
            },
            ],
    "2022":[
          {'nom':"L'Ecailler du Bistrot",
            'num':22,
            'rue':'Rue Paul Bert',
            'lat':48.852433,
            'lon':2.38499,
            'pos': 1,
            'note': 4.4,
            'votes':98
            },
           
            {'nom':'PavYllon',
            'num': 8,
            'rue':'Av. Dutuit',
            'lat':48.865974,
            'lon':2.315667,
            'pos': 2,
            'note': 4.5,
            'votes':850
            },
            {'nom':'Benoit Paris',
            'num':20,
            'rue':'Rue Saint-Martin',
            'lat':48.85842,
            'lon':2.3500601,
            'pos': 3,
            'note': 4.2,
            'votes':1145
            },
            {'nom':"L'As du Fallafel",
            'num':34,
            'rue':'Rue des Rosiers',
            'lat':48.85741,
            'lon':2.359049,
            'pos': 4,
            'note': 4.4,
            'votes':11346
            },
            {'nom':'Eataly',
            'num': 37,
            'rue':'Rue Sainte-Croix de la Bretonnerie',
            'lat': 48.858673,
            'lon':2.354529,
            'pos': 5,
            'note': 4.4,
            'votes':9000
            },
            {'nom':'COMPTOIR GOURMET',
            'num':51,
            'rue':'Rue du Temple',
            'lat':48.865974,
            'lon':2.315667,
            'pos': 6,
            'note': 3.7,
            'votes':584
            },
            {
        'nom':'Bistrot Tao',
        'num': 126,
        'rue':'Rue du Molinel',
        'lat':50.634626,
        'lon':3.068438,
        'pos': 9,
        'note': 4.5,
        'votes':547
    },
    {
        'nom':'KISORO',
        'num': 146,
        'rue':'Rue du Molinel',
        'lat':50.634626,
        'lon':3.068438,
        'pos': 10,
        'note': 4.6,
        'votes':411
    },
    {
        'nom':'Moshi moshi',
        'num': 145,
        'rue':'Rue du Molinel',
        'lat':50.634626,
        'lon':3.068438,
        'pos': 11,
        'note': 4.6,
        'votes':808
    },
           
                         
                         
    ],
               
         



}
